name: teste
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # Service locator
  get_it: ^7.6.6
  # Bloc for state management
  flutter_bloc: ^8.1.3
  # Value equality
  equatable: ^2.0.5
  # Functional programming thingies
  dartz: ^0.10.1 
  # Remote API
  connectivity: ^3.0.6
  http: ^1.1.2
  # Local cache
  shared_preferences: ^2.2.2
  rxdart: ^0.27.7

dev_dependencies:
  bloc_test: ^9.0.2
  build_runner: ^2.4.8
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  mocktail: ^1.0.2
  flutter_lints: ^3.0.1
  

flutter:
    uses-material-design: true



